 @baseUrl = http://localhost:7070/api/v1

### GET request to example server
GET {{baseUrl}}

###

### POST request to example server
POST {{baseUrl}}/users


###


### GET request to example server
GET {{baseUrl}}/users

###

### GET by ID
 GET{{baseUrl}}/users/4

###

### PUT request to example server
PUT {{baseUrl}}/users/9



###

### DELETE request to example server
DELETE {{baseUrl}}/users/9


###
