 @baseUrl = http://localhost:7070/api/v1

### GET request to example server
GET {{baseUrl}}

###

### POST request to example server
POST {{baseUrl}}/employees

 {
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "phone": "12345678",
    "role": "TECHNICIAN",
    "password": "testPassword123"
 }

###


### GET request to example server
GET {{baseUrl}}/employees

###

### GET by ID
 GET {{baseUrl}}/employees/51

###

### PUT request to example server
PUT {{baseUrl}}/employees/51

 {
    "firstName": "John-Updated",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "phone": "12345678",
    "role": "TECHNICIAN",
    "active": true
 }

###

### DELETE request to example server
DELETE {{baseUrl}}/employees/9


###
